github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/tiktok-downloader",
"https://serp.co/products/tiktok-downloader",
"https://store.serp.co/product-details/product/tiktok-downloader",
]
